import {connect} from './client.js';
import {renderPreferences} from './family-preferences.js';
const family=location.pathname.split('/').filter(Boolean).at(-1);const section=document.createElement('section');section.id='ride-choices';section.innerHTML='<h2>🌟 Our family’s wishes & needs</h2><p>Choose rides for each person. Trevor can see your saved choices in the trip planner. These are wishes, not bookings; availability and ride requirements can change before 2029.</p><p role="status">Connecting…</p><div class="choice-list"></div><button type="button" hidden>Save family preferences</button>';
document.querySelector('main').append(section);const status=section.querySelector('[role=status]'),list=section.querySelector('.choice-list'),button=section.querySelector('button');let response={},client,sha=null,choices={},timer,busy=false,saved='',conflict=false;
async function save(){clearTimeout(timer);if(busy||conflict||JSON.stringify(response)===saved)return;busy=true;const snapshot=JSON.stringify(response);status.textContent='Saving your wishes…';try{const result=await client.api('/responses/'+family,{method:'PUT',body:JSON.stringify({sha,data:JSON.parse(snapshot)})});sha=result.sha;saved=snapshot;status.textContent='Saved to GitHub. Trevor can see your choices.'}catch(e){conflict=e.status===409;status.textContent=e.message+' Keep this page open; your changes are not saved yet.'}finally{busy=false;if(!conflict&&saved===snapshot&&JSON.stringify(response)!==saved)timer=setTimeout(save,1500)}}
try{client=await connect(family);if(!client.authenticated){status.textContent='Open the personal family link Trevor shared to choose and save rides. No account or code entry is needed.'}else{const [catalog,state]=await Promise.all([client.api('/catalog'),client.api('/responses/'+family)]);sha=state.sha;response=state.data||{choices:{}};choices=response.choices;response.avoid??={};for(const person of catalog.people){choices[person.id]??=[];const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent=person.name;details.append(summary);for(const park of [...new Set(catalog.rides.map(r=>r.park))]){const heading=document.createElement('h3');heading.textContent=park;details.append(heading);for(const ride of catalog.rides.filter(r=>r.park===park)){const label=document.createElement('label');label.style.cssText='display:block;padding:8px 0';const check=document.createElement('select');check.style.cssText='display:block;max-width:100%;padding:10px;font:inherit;margin-top:6px';check.setAttribute('aria-label',person.name+' — '+ride.name);for(const [value,title] of [['','No preference'],['want','Top ride — want to go'],['avoid','Do not want to go']])check.append(new Option(title,value));check.value=choices[person.id].includes(ride.id)?'want':(response.avoid[person.id]||[]).includes(ride.id)?'avoid':'';check.onchange=()=>{choices[person.id]=choices[person.id].filter(r=>r!==ride.id);response.avoid[person.id]=(response.avoid[person.id]||[]).filter(r=>r!==ride.id);if(check.value==='want')choices[person.id].push(ride.id);if(check.value==='avoid')response.avoid[person.id].push(ride.id);changed()};label.append(document.createTextNode(ride.name+' '),check);details.append(label)}}list.append(details)}renderPreferences(list,catalog,response,changed);await refreshGuide();saved=JSON.stringify(response);button.hidden=false;button.onclick=save;status.textContent=state.data?'Your saved wishes are ready to edit.':'Choose your rides; changes save automatically.'}}catch(e){status.textContent=e.message}
window.addEventListener('beforeunload',e=>{if(JSON.stringify(response)!==saved&&client?.authenticated){e.preventDefault();e.returnValue=''}});

function changed(){status.textContent='Unsaved changes…';clearTimeout(timer);timer=setTimeout(save,1500)}
async function refreshGuide(){
 const guide=await client.api('/guide');
 const root=document.querySelector('#days');
 if(guide.days.length){root.querySelectorAll(':scope > details, :scope > section:not(#ride-choices)').forEach(e=>e.remove());const live=document.createElement('div');live.id='live-days';root.querySelector('#live-days')?.remove();guide.days.forEach((day,index)=>{const detail=document.createElement('details'),title=document.createElement('summary');title.textContent='Day '+(index+1)+' · '+day.title;detail.append(title);for(const event of day.events){const row=document.createElement('article'),time=document.createElement('strong'),content=document.createElement('div');time.textContent=event.time||'TBD';const name=document.createElement('strong');name.textContent=event.name;const place=document.createElement('p');place.textContent=(event.place||'Meeting place to be confirmed')+' · '+event.status;content.append(name,place);row.append(time,content);detail.append(row)}if(!day.events.length){const p=document.createElement('p');p.textContent='Meeting times are being arranged.';detail.append(p)}if(day.dinner){const p=document.createElement('p');p.textContent='Your couple dinner: '+day.dinner+' · proposed, reservation to be confirmed.';detail.append(p)}live.append(detail)});root.append(live)}
 if(guide.hotels.length){const stay=document.querySelector('#stay');stay.querySelectorAll('p').forEach(e=>e.remove());for(const hotel of guide.hotels){const p=document.createElement('p');p.textContent=hotel.name+' — '+hotel.room+' · proposed; booking to be confirmed.';stay.append(p)}}
}

