import {connect} from './client.js';
const family=location.pathname.split('/').filter(Boolean).at(-1);const section=document.createElement('section');section.id='ride-choices';section.innerHTML='<h2>🎢 Our family’s ride wishes</h2><p>Choose rides for each person. Trevor can see your saved choices in the trip planner. These are wishes, not bookings; availability and ride requirements can change before 2029.</p><p role="status">Connecting…</p><div class="choice-list"></div><button type="button" hidden>Save ride choices</button>';
document.querySelector('#days').append(section);const status=section.querySelector('[role=status]'),list=section.querySelector('.choice-list'),button=section.querySelector('button');let client,sha=null,choices={},timer,busy=false,saved='',conflict=false;
async function save(){clearTimeout(timer);if(busy||conflict||JSON.stringify(choices)===saved)return;busy=true;const snapshot=JSON.stringify(choices);status.textContent='Saving your wishes…';try{const result=await client.api('/responses/'+family,{method:'PUT',body:JSON.stringify({sha,data:{choices:JSON.parse(snapshot)}})});sha=result.sha;saved=snapshot;status.textContent='Saved to GitHub. Trevor can see your choices.'}catch(e){conflict=e.status===409;status.textContent=e.message+' Keep this page open; your changes are not saved yet.'}finally{busy=false;if(!conflict&&saved===snapshot&&JSON.stringify(choices)!==saved)timer=setTimeout(save,1500)}}
try{client=await connect(family);if(!client.authenticated){status.textContent='Open the personal family link Trevor shared to choose and save rides. No account or code entry is needed.'}else{const [catalog,state]=await Promise.all([client.api('/catalog'),client.api('/responses/'+family)]);sha=state.sha;choices=state.data?.choices||{};for(const person of catalog.people){choices[person.id]??=[];const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent=person.name;details.append(summary);for(const park of [...new Set(catalog.rides.map(r=>r.park))]){const heading=document.createElement('h3');heading.textContent=park;details.append(heading);for(const ride of catalog.rides.filter(r=>r.park===park)){const label=document.createElement('label');label.style.cssText='display:block;padding:8px 0';const check=document.createElement('input');check.type='checkbox';check.checked=choices[person.id].includes(ride.id);check.onchange=()=>{choices[person.id]=check.checked?[...new Set([...choices[person.id],ride.id])]:choices[person.id].filter(r=>r!==ride.id);status.textContent='Unsaved changes…';clearTimeout(timer);timer=setTimeout(save,1500)};label.append(check,document.createTextNode(' '+ride.name));details.append(label)}}list.append(details)}await refreshGuide();saved=JSON.stringify(choices);button.hidden=false;button.onclick=save;status.textContent=state.data?'Your saved wishes are ready to edit.':'Choose your rides; changes save automatically.'}}catch(e){status.textContent=e.message}
window.addEventListener('beforeunload',e=>{if(JSON.stringify(choices)!==saved&&client?.authenticated){e.preventDefault();e.returnValue=''}});

async function refreshGuide(){
 const guide=await client.api('/guide');
 const root=document.querySelector('#days');
 if(guide.days.length){root.querySelectorAll(':scope > details, :scope > section:not(#ride-choices)').forEach(e=>e.remove());const live=document.createElement('div');live.id='live-days';root.querySelector('#live-days')?.remove();guide.days.forEach((day,index)=>{const detail=document.createElement('details'),title=document.createElement('summary');title.textContent='Day '+(index+1)+' · '+day.title;detail.append(title);for(const event of day.events){const row=document.createElement('article'),time=document.createElement('strong'),content=document.createElement('div');time.textContent=event.time||'TBD';const name=document.createElement('strong');name.textContent=event.name;const place=document.createElement('p');place.textContent=(event.place||'Meeting place to be confirmed')+' · '+event.status;content.append(name,place);row.append(time,content);detail.append(row)}if(!day.events.length){const p=document.createElement('p');p.textContent='Meeting times are being arranged.';detail.append(p)}if(day.dinner){const p=document.createElement('p');p.textContent='Your couple dinner: '+day.dinner+' · proposed, reservation to be confirmed.';detail.append(p)}live.append(detail)});root.insertBefore(live,section)}
 if(guide.hotels.length){const stay=document.querySelector('#stay');stay.querySelectorAll('p').forEach(e=>e.remove());for(const hotel of guide.hotels){const p=document.createElement('p');p.textContent=hotel.name+' — '+hotel.room+' · proposed; booking to be confirmed.';stay.append(p)}}
}

